using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace PxApi.OpenApi.DocumentFilters
{
    /// <summary>
    /// Document filter that removes the ProblemDetails schema from the OpenAPI document.
    /// This schema is auto-generated by Swashbuckle but is not referenced by any response in the API.
    /// </summary>
    public class ProblemDetailsDocumentFilter : IDocumentFilter
    {
        /// <summary>
        /// Removes the ProblemDetails schema from the components section if present.
        /// </summary>
        /// <param name="swaggerDoc">The OpenAPI document to modify.</param>
        /// <param name="context">The document filter context.</param>
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            swaggerDoc.Components?.Schemas?.Remove("ProblemDetails");
        }
    }
}
