namespace PxApi.Utilities
{
    /// <summary>
    /// Tools to help with autogenerated meta codes.
    /// Some codes are generated based on language dependant names and may therefore be unsuitable to be used as codes as is.
    /// </summary>
    public static class MetaCodeTools
    {
        /// <summary>
        /// Extension method that converts any code to an url safe version.
        /// </summary>
        public static string Convert(this string input)
        {
            char[] buffer = new char[input.Length];
            int codeLen = 0;

            for(int i = 0; i < input.Length; i++)
            {
                char deumlaut = DeUmlaut(input[i]);
                if(char.IsAsciiLetterOrDigit(deumlaut))
                {
                    buffer[codeLen] = deumlaut;
                    codeLen++;
                }
                else if (input[i] == '-' || (char.IsWhiteSpace(input[i]) && codeLen > 0 && buffer[codeLen-1] != '-'))
                {
                    buffer[codeLen] = '-';
                    codeLen++;
                }
            }
            return new string(buffer, 0, codeLen);  
        }

        private static char DeUmlaut(char input)
        {
            if (char.ToLowerInvariant(input) == 'ä') return 'a';
            else if (char.ToLowerInvariant(input) == 'ö') return 'o';
            else if (char.ToLowerInvariant(input) == 'å') return 'a';
            return char.ToLowerInvariant(input);
        }
    }
}
